# python of course and we don't need access to sudo atm
language: python
sudo: false

# emails are annoying
notifications:
    email: false

# build on Ubuntu 14.04 because the default is
# really old
os: linux
dist: trusty

# test on the latest version of python
python:
    - "3.6"

# only run travis on selected branches
branches:
    only:
        - master
        - redo
# install dependencies listed in requirements
install: "pip install -r requirements.txt"

# alternate
jobs:
  include:
    - script: ./scripts/_8x3x8_encoder.py  4 4 4  # first try 
    - script: ./scripts/_8x3x8_encoder.py  8 8 3  # real try 
    - stage: deploy

# run tests
#script:
#    "python -m pytest"
